##### Program to create two Tensors using Pytorch and display the multiplication of the two as output. 

In [1]:
import torch

# Create two tensors
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

# Multiply the tensors
result = tensor1 * tensor2

# Display the result
print("Tensor 1:")
print(tensor1)
print("\nTensor 2:")
print(tensor2)
print("\nMultiplication Result:")
print(result)

Tensor 1:
tensor([[1, 2],
        [3, 4]])

Tensor 2:
tensor([[5, 6],
        [7, 8]])

Multiplication Result:
tensor([[ 5, 12],
        [21, 32]])


##### Program to use PyTorch to perform Backward pass and gradient computation.

In [2]:
import torch

# Create a tensor with requires_grad set to True
x = torch.tensor(3.0, requires_grad=True)

# Define a function y = x^2
y = x**2

# Perform backward pass
y.backward()

# Print the gradient of x
print("Gradient of x:", x.grad)

Gradient of x: tensor(6.)


##### Program to showcase the usage of PyTorch's TensorDataset and DataLoader classes for creating a dataset and dataloader from NumPy arrays. After executing this code, you will have a dataset (my_dataset) and a dataloader (my_dataloader) ready to be used for training or inference. 

In [3]:

import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader

# Create NumPy arrays for features and labels
features = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])
labels = np.array([0, 1, 0])

# Convert NumPy arrays to PyTorch tensors
features_tensor = torch.tensor(features, dtype=torch.float32)
labels_tensor = torch.tensor(labels, dtype=torch.int64)

# Create a TensorDataset
my_dataset = TensorDataset(features_tensor, labels_tensor)

# Create a DataLoader
batch_size = 2
my_dataloader = DataLoader(my_dataset, batch_size=batch_size, shuffle=True)

# Print some batches from the dataloader
for batch_features, batch_labels in my_dataloader:
    print("Batch Features:")
    print(batch_features)
    print("Batch Labels:")
    print(batch_labels)
    print("-" * 20)

Batch Features:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
Batch Labels:
tensor([0, 1])
--------------------
Batch Features:
tensor([[7., 8., 9.]])
Batch Labels:
tensor([0])
--------------------


##### Implement a simple neural network using PyTorch to train on a randomly generated dataset. Customize & Update the weights using an optimizer in PyTorch, to improve the model’s accuracy.

In [4]:
import torch
import torch.nn as nn
import torch.optim as optim

# Generate a random dataset
torch.manual_seed(42)
features = torch.randn(100, 2)
labels = (features[:, 0] * 3 + features[:, 1] * 2 + torch.randn(100)) > 0

# Define a simple neural network class
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 1)  # Input features: 2, Output features: 1
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, x):
        x = self.fc1(x)
        x = self.sigmoid(x)
        return x

# Create an instance of the neural network
model = SimpleNN()

# Define loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross Entropy Loss
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
epochs = 1000
for epoch in range(epochs):
    # Forward pass
    outputs = model(features)
    loss = criterion(outputs.squeeze(), labels.float())
    
    # Backpropagation and optimization
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    if (epoch + 1) % 100 == 0:
        print(f'Epoch [{epoch+1}/{epochs}], Loss: {loss.item():.4f}')

# Evaluate the model
with torch.no_grad():
    test_features = torch.randn(10, 2)
    predicted_labels = model(test_features).squeeze().round()
    print("Predicted Labels:", predicted_labels)

Epoch [100/1000], Loss: 0.3328
Epoch [200/1000], Loss: 0.2690
Epoch [300/1000], Loss: 0.2429
Epoch [400/1000], Loss: 0.2281
Epoch [500/1000], Loss: 0.2183
Epoch [600/1000], Loss: 0.2113
Epoch [700/1000], Loss: 0.2060
Epoch [800/1000], Loss: 0.2018
Epoch [900/1000], Loss: 0.1984
Epoch [1000/1000], Loss: 0.1957
Predicted Labels: tensor([1., 1., 0., 0., 1., 0., 0., 0., 1., 1.])


##### Program that uses cv2 and rotates an image. The code will create three images: "tester1.png", "tester2.png", and "tester3.png”. Each image will be a variation of the original image based on the applied pixel assignment patterns such that the resulting image is rotated at 90°, 180°, 270° respectively.

In [10]:
import cv2

# Load the original image
original_image = cv2.imread('image.jpg')

# Rotate the image by 90 degrees
rotated_90 = cv2.rotate(original_image, cv2.ROTATE_90_CLOCKWISE)

# Rotate the image by 180 degrees
rotated_180 = cv2.rotate(original_image, cv2.ROTATE_180)

# Rotate the image by 270 degrees (90 degrees counterclockwise)
rotated_270 = cv2.rotate(original_image, cv2.ROTATE_90_COUNTERCLOCKWISE)

# Save the rotated images
cv2.imwrite('tester1.png', rotated_90)
cv2.imwrite('tester2.png', rotated_180)
cv2.imwrite('tester3.png', rotated_270)

print("Images saved successfully.")

Images saved successfully.


In [14]:
from IPython.display import Image, display, HTML

def display_images_side_by_side(images, width):
    img_html = ''
    for img_path in images:
        img_html += f'<img src="{img_path}" style="display:inline-block; margin: 0 10px; width: {width}px;">'
    display(HTML(img_html))


images = ['image.jpg', 'tester1.png', 'tester2.png', 'tester3.png']
display_images_side_by_side(images, width = 200)
